# Docker 镜像构建
# Runtime stage
FROM node:16.20.1-bullseye-slim

# Build the React frontend
COPY napi-hub-frontend /app/napi-hub-frontend
WORKDIR /app/napi-hub-frontend
RUN yarn install && \
    yarn build
EXPOSE 8000

# Size: 2.83G